apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${IMAGE}-${VERSION}
spec:
  selector:
    matchLabels:
      app: ${IMAGE}-${VERSION}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${IMAGE}-${VERSION}
    spec:
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: minecraft-${TYPE}-log-${VERSION}
      - name: backups 
        persistentVolumeClaim:
          claimName: minecraft-${TYPE}-backups-${VERSION}
      - name: world 
        persistentVolumeClaim:
          claimName: minecraft-${TYPE}-world-${VERSION}
      containers:
      - name: ${IMAGE}
        image: ${IMAGE}:${VERSION}
        imagePullPolicy: Never        
        envFrom:
        - configMapRef:
            name: ${IMAGE}-${VERSION}
        volumeMounts:
        - mountPath: /opt/minecraft/log
          name: log
        - mountPath: /opt/minecraft/backups
          name: backups 
        - mountPath: "${WORLD_BASE}/${WORLD_NAME}"
          name: world 
        ports:
        - containerPort: 19132
          name: default 
---
apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE}-service-udp-${VERSION_HYPHEN}
  # labels:
  #   kubernetes.io/minikube-addons-endpoint: ingress
spec:
  type: NodePort
  ports:
    - name: default
      port: 19132
      targetPort: default
      protocol: UDP
  selector:
    app: ${IMAGE}
---
apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE}-service-tcp-${VERSION_HYPHEN}
  # labels:
  #   kubernetes.io/minikube-addons-endpoint: ingress
spec:
  type: NodePort
  ports:
    - name: default
      port: 19132
      targetPort: default
      protocol: TCP
  selector:
    app: ${IMAGE}
