apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bitnami/kubectl:1.24
            imagePullPolicy: IfNotPresent
            command:
            - kubectl
            - get
            - pods
          restartPolicy: Never
          concurrencyPolicy: Forbid
          failedJobsHistoryLimit: 5