apiVersion: v1
kind: PersistentVolume 
metadata:
  name: minecraft-${TYPE}-log-pv-${VERSION}-${WORLD_NAME}
spec:
  capacity: 
    storage: 10Gi
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: standard 
  local:
    path: ${VOLUME_BASE}-${VERSION}/${WORLD_NAME}/log
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname 
          operator: In 
          values:
          - minikube
---          
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: minecraft-${TYPE}-backups-pv-${VERSION}-${WORLD_NAME}
spec:
  capacity: 
    storage: 10Gi
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: standard 
  local:
    path: ${VOLUME_BASE}-${VERSION}/${WORLD_NAME}/backups
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname 
          operator: In 
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: minecraft-${TYPE}-world-pv-${VERSION}-${WORLD_NAME}
spec:
  capacity: 
    storage: 10Gi
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: standard 
  local:
    path: ${VOLUME_BASE}-${VERSION}/${WORLD_NAME}/world
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname 
          operator: In 
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: minecraft-${TYPE}-log-${VERSION}-${WORLD_NAME}
spec:
  volumeName: minecraft-${TYPE}-log-pv-${VERSION}-${WORLD_NAME}
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi   
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: minecraft-${TYPE}-backups-${VERSION}-${WORLD_NAME}
spec:
  volumeName: minecraft-${TYPE}-backups-pv-${VERSION}-${WORLD_NAME}
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: minecraft-${TYPE}-world-${VERSION}-${WORLD_NAME}
spec:
  volumeName: minecraft-${TYPE}-world-pv-${VERSION}-${WORLD_NAME}
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---